dist: xenial
os: linux
language: java
cache:
  directories:
  - "~/.m2"
branches:
  only:
  - master
  - development
install: ''
jobs:
  fast_finish: true
  include:
  - jdk: openjdk11
    env:
    - DESC="build with OPENJDK11"
    - USE_MAVEN_REPO="true"
    - CMD="mvn clean package"
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}
script:
- "mvn clean package -B"