server:
  type: default

template: Hello, %s!
defaultName: Stranger

database:
  driverClass: org.h2.Driver
  user: sa
  password:
  url: jdbc:h2:file:D:/data/demodb
  validationQuery: "select 1"
  properties:
    hibernate.dialect: org.hibernate.dialect.H2Dialect

schedulerConfig:
  initialDelayinMin: 0
  delayInMin: 2

#database:
# driverClass: oracle.jdbc.OracleDriver
# user: system
# password: oracle
# url: jdbc:oracle:thin:@localhost:1521:xe
# maxWaitForConnection: 1s
# validationQuery: "/* MyService Health Check */ select 1 from dual"
# minSize: 8
# maxSize: 32
# checkConnectionWhileIdle: false
# evictionInterval: 10s
# minIdleTime: 1 minute
# properties:
#   charSet: UTF-8
#   hibernate.dialect: org.hibernate.dialect.Oracle12cDialect
#   hibernate.show_sql: true
#   hibernate.generate_statistics: false
#   hibernate.hbm2ddl.auto: validate # validates schema when service is started
